# Generated by Django 2.0.2 on 2018-03-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_article_allow_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='allow_comments',
        ),
    ]
