# Generated by Django 2.0.2 on 2018-03-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_article_allow_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
