# Generated by Django 2.0.2 on 2018-03-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
